# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/linyingjie/work/c-projects/libhttpserver/CMakeFiles/3.17.3/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/linyingjie/work/c-projects/libhttpserver/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/UnixPaths.cmake))

/Users/linyingjie/work/c-projects/libhttpserver/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.3/bin/cmake -H/Users/linyingjie/work/c-projects/libhttpserver -B/Users/linyingjie/work/c-projects/libhttpserver
